"""Add new tables or changes

Revision ID: 762ed12ed483
Revises: 0a6188e67b9b
Create Date: 2024-11-28 10:19:00.645646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762ed12ed483'
down_revision = '0a6188e67b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('location_x', sa.Float(), nullable=True),
    sa.Column('location_y', sa.Float(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['game_room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=80), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    op.drop_table('resource')
    # ### end Alembic commands ###
